name: Deploy

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Discord GitHub Roles
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            echo "🔑 Cloning repository..."
            cd discord-github-roles
            GIT_SSH_COMMAND='ssh -i ~/.ssh/discord_github_roles_rsa' git pull
            GIT_SSH_COMMAND='ssh -i ~/.ssh/discord_github_roles_rsa' git reset --hard origin/main

            echo "🚀 Building application..."
            docker compose -f docker-compose-prod.yml down
            docker compose -f docker-compose-prod.yml up -d --build

            # Wait for application to be ready
            echo "⏳ Waiting for application to start..."
            for i in {1..12}; do
              if curl -s http://localhost:3420/api/health > /dev/null; then
                echo "✅ Application is ready!"
                
                echo "📝 Running migrations..."
                docker compose -f docker-compose-migrate.yml up -d
                exit 0
              fi
              echo "Attempt $i/12: Application not ready, waiting..."
              sleep 5
            done

            echo "❌ Application failed to start"
            docker compose -f docker-compose-prod.yml logs
            exit 1
